# Generated by Django 4.0.6 on 2022-07-05 22:39

import client.models.user
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(blank=True, unique=True, verbose_name='Укажите endpoint')),
                ('params', models.ManyToManyField(to='client.EndpointParameters', verbose_name='Параметры ')),
            ],
            options={
                'db_table': 'endpoint',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('username', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Пользователь')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('hide_personal_data', models.BooleanField(blank=True, default=False, verbose_name='Скрыть персональные данные:')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Мобильный номер телефона')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли сотрудником')),
                ('is_supervisor', models.BooleanField(default=False, verbose_name='Является ли руководителем')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
            managers=[
                ('objects', client.models.user.UserManager()),
            ],
        ),
    ]
