# Generated by Django 4.0.6 on 2022-07-05 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=64, verbose_name='Токен авторизации')),
                ('client_id', models.CharField(blank=True, max_length=64, verbose_name='Публичный ключ')),
                ('client_secret', models.CharField(blank=True, max_length=64, verbose_name='Секретный ключ')),
                ('grant_type', models.CharField(blank=True, default='client_credentials', max_length=64, verbose_name='Тип гранта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Данные авторизации',
                'verbose_name_plural': 'Данные авторизации',
                'db_table': 'authorizations_data',
            },
        ),
    ]
