# Generated by Django 4.0.6 on 2022-07-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_authorizationsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания токена'),
        ),
        migrations.AddField(
            model_name='authorizationdata',
            name='expires_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Истекает'),
        ),
        migrations.AddField(
            model_name='authorizationdata',
            name='resource_owner_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор владельца ресурса'),
        ),
        migrations.AddField(
            model_name='authorizationdata',
            name='token_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='Тип токена'),
        ),
        migrations.AlterModelTable(
            name='authorizationdata',
            table='authorization_data',
        ),
    ]
